[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["cd core && composer install --no-dev --optimize-autoloader"]

[start]
cmd = "cd core && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
