[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = [
  "cd Files/core && composer install --no-dev --optimize-autoloader --no-scripts"
]

[phases.build]
cmds = [
  "cd Files/core && cp .env.example .env",
  "cd Files/core && echo 'APP_NAME=\"HYIP Lab\"' > .env",
  "cd Files/core && echo 'APP_ENV=production' >> .env",
  "cd Files/core && echo \"APP_KEY=${APP_KEY}\" >> .env",
  "cd Files/core && echo 'APP_DEBUG=false' >> .env",
  "cd Files/core && echo 'APP_TIMEZONE=UTC' >> .env",
  "cd Files/core && echo \"APP_URL=${APP_URL}\" >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'APP_LOCALE=en' >> .env",
  "cd Files/core && echo 'APP_FALLBACK_LOCALE=en' >> .env",
  "cd Files/core && echo 'APP_FAKER_LOCALE=en_US' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'APP_MAINTENANCE_DRIVER=file' >> .env",
  "cd Files/core && echo 'APP_MAINTENANCE_STORE=database' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'BCRYPT_ROUNDS=12' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'LOG_CHANNEL=stack' >> .env",
  "cd Files/core && echo 'LOG_STACK=single' >> .env",
  "cd Files/core && echo 'LOG_DEPRECATIONS_CHANNEL=null' >> .env",
  "cd Files/core && echo 'LOG_LEVEL=error' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'DB_CONNECTION=mysql' >> .env",
  "cd Files/core && echo \"DB_HOST=${MYSQLHOST:-mysql.railway.internal}\" >> .env",
  "cd Files/core && echo \"DB_PORT=${MYSQLPORT:-3306}\" >> .env",
  "cd Files/core && echo \"DB_DATABASE=${MYSQLDATABASE:-railway}\" >> .env",
  "cd Files/core && echo \"DB_USERNAME=${MYSQLUSER:-root}\" >> .env",
  "cd Files/core && echo \"DB_PASSWORD=${MYSQLPASSWORD}\" >> .env",
  "cd Files/core && echo 'DB_SOCKET=' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'SESSION_DRIVER=database' >> .env",
  "cd Files/core && echo 'SESSION_LIFETIME=120' >> .env",
  "cd Files/core && echo 'SESSION_ENCRYPT=false' >> .env",
  "cd Files/core && echo 'SESSION_PATH=/' >> .env",
  "cd Files/core && echo 'SESSION_DOMAIN=null' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'BROADCAST_CONNECTION=log' >> .env",
  "cd Files/core && echo 'FILESYSTEM_DISK=local' >> .env",
  "cd Files/core && echo 'QUEUE_CONNECTION=database' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'CACHE_STORE=database' >> .env",
  "cd Files/core && echo 'CACHE_PREFIX=' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'MAIL_MAILER=log' >> .env",
  "cd Files/core && echo 'MAIL_HOST=127.0.0.1' >> .env",
  "cd Files/core && echo 'MAIL_PORT=2525' >> .env",
  "cd Files/core && echo 'MAIL_USERNAME=null' >> .env",
  "cd Files/core && echo 'MAIL_PASSWORD=null' >> .env",
  "cd Files/core && echo 'MAIL_ENCRYPTION=null' >> .env",
  "cd Files/core && echo 'MAIL_FROM_ADDRESS=\"hello@example.com\"' >> .env",
  "cd Files/core && echo 'MAIL_FROM_NAME=\"${APP_NAME}\"' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'VITE_APP_NAME=\"${APP_NAME}\"' >> .env"
]

[start]
cmd = "cd Files/core && php artisan config:clear && php artisan cache:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
