[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mysqli",
  "php83Extensions.mbstring",
  "php83Extensions.xml",
  "php83Extensions.curl",
  "php83Extensions.gd",
  "php83Extensions.zip",
  "php83Extensions.bcmath",
  "php83Extensions.intl",
  "php83Extensions.fileinfo",
  "php83Extensions.tokenizer",
  "php83Extensions.ctype",
  "php83Extensions.json",
  "php83Extensions.openssl",
  "php83Extensions.session"
]

[phases.install]
cmds = [
  "cd Files/core && composer install --no-dev --optimize-autoloader --no-scripts"
]

[phases.build]
cmds = [
  "cd Files/core && cp .env.example .env",
  "cd Files/core && echo 'APP_NAME=\"HYIP Lab\"' > .env",
  "cd Files/core && echo 'APP_ENV=production' >> .env",
  "cd Files/core && echo \"APP_KEY=${APP_KEY}\" >> .env",
  "cd Files/core && echo 'APP_DEBUG=false' >> .env",
  "cd Files/core && echo 'APP_TIMEZONE=UTC' >> .env",
  "cd Files/core && echo \"APP_URL=${APP_URL}\" >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'APP_LOCALE=en' >> .env",
  "cd Files/core && echo 'APP_FALLBACK_LOCALE=en' >> .env",
  "cd Files/core && echo 'APP_FAKER_LOCALE=en_US' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'APP_MAINTENANCE_DRIVER=file' >> .env",
  "cd Files/core && echo 'APP_MAINTENANCE_STORE=database' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'BCRYPT_ROUNDS=12' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'LOG_CHANNEL=stack' >> .env",
  "cd Files/core && echo 'LOG_STACK=single' >> .env",
  "cd Files/core && echo 'LOG_DEPRECATIONS_CHANNEL=null' >> .env",
  "cd Files/core && echo 'LOG_LEVEL=debug' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'DB_CONNECTION=mysql' >> .env",
  "cd Files/core && echo \"DB_HOST=${MYSQLHOST}\" >> .env",
  "cd Files/core && echo \"DB_PORT=${MYSQLPORT}\" >> .env",
  "cd Files/core && echo \"DB_DATABASE=${MYSQLDATABASE}\" >> .env",
  "cd Files/core && echo \"DB_USERNAME=${MYSQLUSER}\" >> .env",
  "cd Files/core && echo \"DB_PASSWORD=${MYSQLPASSWORD}\" >> .env",
  "cd Files/core && echo 'DB_SOCKET=' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'SESSION_DRIVER=database' >> .env",
  "cd Files/core && echo 'SESSION_LIFETIME=120' >> .env",
  "cd Files/core && echo 'SESSION_ENCRYPT=false' >> .env",
  "cd Files/core && echo 'SESSION_PATH=/' >> .env",
  "cd Files/core && echo 'SESSION_DOMAIN=null' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'BROADCAST_CONNECTION=log' >> .env",
  "cd Files/core && echo 'FILESYSTEM_DISK=local' >> .env",
  "cd Files/core && echo 'QUEUE_CONNECTION=database' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'CACHE_STORE=database' >> .env",
  "cd Files/core && echo 'CACHE_PREFIX=' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'MAIL_MAILER=log' >> .env",
  "cd Files/core && echo 'MAIL_HOST=127.0.0.1' >> .env",
  "cd Files/core && echo 'MAIL_PORT=2525' >> .env",
  "cd Files/core && echo 'MAIL_USERNAME=null' >> .env",
  "cd Files/core && echo 'MAIL_PASSWORD=null' >> .env",
  "cd Files/core && echo 'MAIL_ENCRYPTION=null' >> .env",
  "cd Files/core && echo 'MAIL_FROM_ADDRESS=\"hello@example.com\"' >> .env",
  "cd Files/core && echo 'MAIL_FROM_NAME=\"${APP_NAME}\"' >> .env",
  "cd Files/core && echo '' >> .env",
  "cd Files/core && echo 'VITE_APP_NAME=\"${APP_NAME}\"' >> .env",
  "cd Files/core && mkdir -p storage/framework/{sessions,views,cache}",
  "cd Files/core && mkdir -p storage/logs",
  "cd Files/core && mkdir -p bootstrap/cache",
  "cd Files/core && chmod -R 775 storage bootstrap/cache",
  "chmod +x start.sh"
]

[start]
cmd = "bash start.sh"
