[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["cd Files/core && composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["cd Files/core && php artisan config:cache"]

[start]
cmd = "cd Files/core && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
